context("  Row NAs")

test_that("row_nas for integer matrices works.", {
    expected <- apply(int_na_mat, 1L, function(x) { all(is.na(x)) })
    ans <- row_nas(int_na_mat, "all")
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "all", output_class = "list")
    expect_identical(ans, as.list(expected))

    expected <- apply(int_na_mat, 1L, function(x) { all(!is.na(x)) })
    ans <- row_nas(int_na_mat, "none")
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "none", output_class = "list")
    expect_identical(ans, as.list(expected))

    expected <- apply(int_na_mat, 1L, function(x) { anyNA(x) })
    ans <- row_nas(int_na_mat, "any")
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "any", output_class = "list")
    expect_identical(ans, as.list(expected))
})

test_that("row_nas for integer matrices with column subset works.", {
    expected <- apply(int_na_mat[, -2L], 1L, function(x) { all(is.na(x)) })
    ans <- row_nas(int_na_mat, "all", cols = c(1, 3))
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "all", cols = -2L)
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "all", cols = c(TRUE, FALSE, TRUE))
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "all", cols = -2.0, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(int_na_mat, "all", cols = integer())
    expect_true(all(!ans))

    expected <- apply(int_na_mat[, -2L], 1L, function(x) { all(!is.na(x)) })
    ans <- row_nas(int_na_mat, "none", cols = c(1, 3))
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "none", cols = -2L)
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "none", cols = c(TRUE, FALSE, TRUE))
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "none", cols = -2.0, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(int_na_mat, "none", cols = integer())
    expect_true(all(ans))

    expected <- apply(int_na_mat[, -2L], 1L, function(x) { anyNA(x) })
    ans <- row_nas(int_na_mat, "any", cols = c(1, 3))
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "any", cols = -2L)
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "any", cols = c(TRUE, FALSE, TRUE))
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "any", cols = -2.0, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(int_na_mat, "any", cols = integer())
    expect_true(all(!ans))
})

test_that("row_nas for integer matrices with row subset works.", {
    expected <- apply(int_na_mat[1001:2000,], 1L, function(x) { all(is.na(x)) })
    ans <- row_nas(int_na_mat, "all", rows = 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "all", rows = 1:5000 %in% 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "all", rows = -c(1:1000, 2001:5000))
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "all", rows = 1001:2000, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(int_na_mat, "all", rows = integer())
    expect_identical(ans, logical())

    expected <- apply(int_na_mat[1001:2000,], 1L, function(x) { all(!is.na(x)) })
    ans <- row_nas(int_na_mat, "none", rows = 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "none", rows = 1:5000 %in% 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "none", rows = -c(1:1000, 2001:5000))
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "none", rows = 1001:2000, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(int_na_mat, "none", rows = integer())
    expect_identical(ans, logical())

    expected <- apply(int_na_mat[1001:2000,], 1L, function(x) { anyNA(x) })
    ans <- row_nas(int_na_mat, "any", rows = 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "any", rows = 1:5000 %in% 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "any", rows = -c(1:1000, 2001:5000))
    expect_identical(ans, expected)
    ans <- row_nas(int_na_mat, "any", rows = 1001:2000, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(int_na_mat, "any", rows = integer())
    expect_identical(ans, logical())
})

test_that("row_nas for double matrices works.", {
    expected <- apply(dbl_na_mat, 1L, function(x) { all(is.na(x)) })
    ans <- row_nas(dbl_na_mat, "all")
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "all", output_class = "list")
    expect_identical(ans, as.list(expected))

    expected <- apply(dbl_na_mat, 1L, function(x) { all(!is.na(x)) })
    ans <- row_nas(dbl_na_mat, "none")
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "none", output_class = "list")
    expect_identical(ans, as.list(expected))

    expected <- apply(dbl_na_mat, 1L, function(x) { anyNA(x) })
    ans <- row_nas(dbl_na_mat, "any")
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "any", output_class = "list")
    expect_identical(ans, as.list(expected))
})

test_that("row_nas for double matrices with column subset works.", {
    expected <- apply(dbl_na_mat[, -2L], 1L, function(x) { all(is.na(x)) })
    ans <- row_nas(dbl_na_mat, "all", cols = c(1, 3))
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "all", cols = -2L)
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "all", cols = c(TRUE, FALSE, TRUE))
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "all", cols = -2.0, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(dbl_na_mat, "all", cols = integer())
    expect_true(all(!ans))

    expected <- apply(dbl_na_mat[, -2L], 1L, function(x) { all(!is.na(x)) })
    ans <- row_nas(dbl_na_mat, "none", cols = c(1, 3))
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "none", cols = -2L)
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "none", cols = c(TRUE, FALSE, TRUE))
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "none", cols = -2.0, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(dbl_na_mat, "none", cols = integer())
    expect_true(all(ans))

    expected <- apply(dbl_na_mat[, -2L], 1L, function(x) { anyNA(x) })
    ans <- row_nas(dbl_na_mat, "any", cols = c(1, 3))
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "any", cols = -2L)
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "any", cols = c(TRUE, FALSE, TRUE))
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "any", cols = -2.0, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(dbl_na_mat, "any", cols = integer())
    expect_true(all(!ans))
})

test_that("row_nas for double matrices with row subset works.", {
    expected <- apply(dbl_na_mat[1001:2000,], 1L, function(x) { all(is.na(x)) })
    ans <- row_nas(dbl_na_mat, "all", rows = 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "all", rows = 1:5000 %in% 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "all", rows = -c(1:1000, 2001:5000))
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "all", rows = 1001:2000, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(dbl_na_mat, "all", rows = integer())
    expect_identical(ans, logical())

    expected <- apply(dbl_na_mat[1001:2000,], 1L, function(x) { all(!is.na(x)) })
    ans <- row_nas(dbl_na_mat, "none", rows = 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "none", rows = 1:5000 %in% 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "none", rows = -c(1:1000, 2001:5000))
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "none", rows = 1001:2000, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(dbl_na_mat, "none", rows = integer())
    expect_identical(ans, logical())

    expected <- apply(dbl_na_mat[1001:2000,], 1L, function(x) { anyNA(x) })
    ans <- row_nas(dbl_na_mat, "any", rows = 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "any", rows = 1:5000 %in% 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "any", rows = -c(1:1000, 2001:5000))
    expect_identical(ans, expected)
    ans <- row_nas(dbl_na_mat, "any", rows = 1001:2000, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(dbl_na_mat, "any", rows = integer())
    expect_identical(ans, logical())
})

test_that("row_nas for logical matrices works.", {
    expected <- apply(bool_na_mat, 1L, function(x) { all(is.na(x)) })
    ans <- row_nas(bool_na_mat, "all")
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "all", output_class = "list")
    expect_identical(ans, as.list(expected))

    expected <- apply(bool_na_mat, 1L, function(x) { all(!is.na(x)) })
    ans <- row_nas(bool_na_mat, "none")
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "none", output_class = "list")
    expect_identical(ans, as.list(expected))

    expected <- apply(bool_na_mat, 1L, function(x) { anyNA(x) })
    ans <- row_nas(bool_na_mat, "any")
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "any", output_class = "list")
    expect_identical(ans, as.list(expected))
})

test_that("row_nas for logical matrices with column subset works.", {
    expected <- apply(bool_na_mat[, -2L], 1L, function(x) { all(is.na(x)) })
    ans <- row_nas(bool_na_mat, "all", cols = c(1, 3))
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "all", cols = -2L)
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "all", cols = c(TRUE, FALSE, TRUE))
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "all", cols = -2.0, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(bool_na_mat, "all", cols = integer())
    expect_true(all(!ans))

    expected <- apply(bool_na_mat[, -2L], 1L, function(x) { all(!is.na(x)) })
    ans <- row_nas(bool_na_mat, "none", cols = c(1, 3))
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "none", cols = -2L)
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "none", cols = c(TRUE, FALSE, TRUE))
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "none", cols = -2.0, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(bool_na_mat, "none", cols = integer())
    expect_true(all(ans))

    expected <- apply(bool_na_mat[, -2L], 1L, function(x) { anyNA(x) })
    ans <- row_nas(bool_na_mat, "any", cols = c(1, 3))
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "any", cols = -2L)
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "any", cols = c(TRUE, FALSE, TRUE))
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "any", cols = -2.0, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(bool_na_mat, "any", cols = integer())
    expect_true(all(!ans))
})

test_that("row_nas for logical matrices with row subset works.", {
    expected <- apply(bool_na_mat[1001:2000,], 1L, function(x) { all(is.na(x)) })
    ans <- row_nas(bool_na_mat, "all", rows = 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "all", rows = 1:5000 %in% 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "all", rows = -c(1:1000, 2001:5000))
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "all", rows = 1001:2000, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(bool_na_mat, "all", rows = integer())
    expect_identical(ans, logical())

    expected <- apply(bool_na_mat[1001:2000,], 1L, function(x) { all(!is.na(x)) })
    ans <- row_nas(bool_na_mat, "none", rows = 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "none", rows = 1:5000 %in% 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "none", rows = -c(1:1000, 2001:5000))
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "none", rows = 1001:2000, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(bool_na_mat, "none", rows = integer())
    expect_identical(ans, logical())

    expected <- apply(bool_na_mat[1001:2000,], 1L, function(x) { anyNA(x) })
    ans <- row_nas(bool_na_mat, "any", rows = 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "any", rows = 1:5000 %in% 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "any", rows = -c(1:1000, 2001:5000))
    expect_identical(ans, expected)
    ans <- row_nas(bool_na_mat, "any", rows = 1001:2000, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(bool_na_mat, "any", rows = integer())
    expect_identical(ans, logical())
})

test_that("row_nas for complex matrices works.", {
    expected <- apply(cplx_na_mat, 1L, function(x) { all(is.na(x)) })
    ans <- row_nas(cplx_na_mat, "all")
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "all", output_class = "list")
    expect_identical(ans, as.list(expected))

    expected <- apply(cplx_na_mat, 1L, function(x) { all(!is.na(x)) })
    ans <- row_nas(cplx_na_mat, "none")
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "none", output_class = "list")
    expect_identical(ans, as.list(expected))

    expected <- apply(cplx_na_mat, 1L, function(x) { anyNA(x) })
    ans <- row_nas(cplx_na_mat, "any")
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "any", output_class = "list")
    expect_identical(ans, as.list(expected))
})

test_that("row_nas for complex matrices with column subset works.", {
    expected <- apply(cplx_na_mat[, -2L], 1L, function(x) { all(is.na(x)) })
    ans <- row_nas(cplx_na_mat, "all", cols = c(1, 3))
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "all", cols = -2L)
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "all", cols = c(TRUE, FALSE, TRUE))
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "all", cols = -2.0, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(cplx_na_mat, "all", cols = integer())
    expect_true(all(!ans))

    expected <- apply(cplx_na_mat[, -2L], 1L, function(x) { all(!is.na(x)) })
    ans <- row_nas(cplx_na_mat, "none", cols = c(1, 3))
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "none", cols = -2L)
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "none", cols = c(TRUE, FALSE, TRUE))
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "none", cols = -2.0, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(cplx_na_mat, "none", cols = integer())
    expect_true(all(ans))

    expected <- apply(cplx_na_mat[, -2L], 1L, function(x) { anyNA(x) })
    ans <- row_nas(cplx_na_mat, "any", cols = c(1, 3))
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "any", cols = -2L)
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "any", cols = c(TRUE, FALSE, TRUE))
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "any", cols = -2.0, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(cplx_na_mat, "any", cols = integer())
    expect_true(all(!ans))
})

test_that("row_nas for complex matrices with row subset works.", {
    expected <- apply(cplx_na_mat[1001:2000,], 1L, function(x) { all(is.na(x)) })
    ans <- row_nas(cplx_na_mat, "all", rows = 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "all", rows = 1:5000 %in% 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "all", rows = -c(1:1000, 2001:5000))
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "all", rows = 1001:2000, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(cplx_na_mat, "all", rows = integer())
    expect_identical(ans, logical())

    expected <- apply(cplx_na_mat[1001:2000,], 1L, function(x) { all(!is.na(x)) })
    ans <- row_nas(cplx_na_mat, "none", rows = 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "none", rows = 1:5000 %in% 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "none", rows = -c(1:1000, 2001:5000))
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "none", rows = 1001:2000, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(cplx_na_mat, "none", rows = integer())
    expect_identical(ans, logical())

    expected <- apply(cplx_na_mat[1001:2000,], 1L, function(x) { anyNA(x) })
    ans <- row_nas(cplx_na_mat, "any", rows = 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "any", rows = 1:5000 %in% 1001:2000)
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "any", rows = -c(1:1000, 2001:5000))
    expect_identical(ans, expected)
    ans <- row_nas(cplx_na_mat, "any", rows = 1001:2000, output_class = "list")
    expect_identical(ans, as.list(expected))

    ans <- row_nas(cplx_na_mat, "any", rows = integer())
    expect_identical(ans, logical())
})

test_that("row_nas for data frames works.", {
    expected <- sapply(4001:5000, df = df, function(i, df) { all(is.na(df[i, , drop = FALSE])) })
    ans <- row_nas(df, "all", rows = 4001:5000)
    expect_identical(ans, expected)
    ans <- row_nas(df, "all", rows = 4001:5000, output_class = "list")
    expect_identical(ans, as.list(expected))

    expected <- sapply(4001:5000, df = df, function(i, df) { all(!is.na(df[i, , drop = FALSE])) })
    ans <- row_nas(df, "none", rows = 4001:5000)
    expect_identical(ans, expected)
    ans <- row_nas(df, "none", rows = 4001:5000, output_class = "list")
    expect_identical(ans, as.list(expected))

    expected <- sapply(4001:5000, df = df, function(i, df) { anyNA(df[i, , drop = FALSE]) })
    ans <- row_nas(df, "any", rows = 4001:5000)
    expect_identical(ans, expected)
    ans <- row_nas(df, "any", rows = 4001:5000, output_class = "list")
    expect_identical(ans, as.list(expected))
})
