context("Unit tests")

source("unit/test-row_sums.R", TRUE)
source("unit/test-row_nas.R", TRUE)
source("unit/test-row_infs.R", TRUE)
source("unit/test-row_finites.R", TRUE)
source("unit/test-row_compare.R", TRUE)
source("unit/test-row_arith.R", TRUE)
source("unit/test-row_in.R", TRUE)
source("unit/test-row_duplicated.R", TRUE)
source("unit/test-row_means.R", TRUE)
source("unit/test-row_extrema.R", TRUE)
source("unit/test-row_max.R", TRUE)
source("unit/test-row_min.R", TRUE)

source("unit/test-misc.R", TRUE)
